[package]
name = "scan-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
dialoguer = "0.11.0"
indicatif = "0.17.7"
ipnetwork = "0.20.0"
pnet = "0.34.0"
